### PR TITLE
Feat import project

### PR DESCRIPTION
**Pull request by michellerenehey**

### CODE REVIEW

**Review by forecasth — COMMENTED** [review]
Looks good

**Review by kakizaki55 — APPROVED** [review]
looks great to me!

**Comment by michellerenehey** [comment]
This pull request moves the app's logic from our working sandbox into our project. The features include: 

- [x]  building, saving, updating a project
- [x] creating channels
- [x]  creating sound modifiers onto each channel (including volume, reverb, and synth type)
- [x]  using project context and reducers to help manage state

Screen Shot 2022-04-18 at 2 07 13 PM

**Review by jlaurentpdx — APPROVED** [review]
Awesome work!

**Pull request merged**
